<?php
define("DS", DIRECTORY_SEPARATOR);
define("BASE", __DIR__);
include __DIR__ . DS . "utils" . DS . "utils.php";
include __DIR__ . DS . "utils" . DS . "date_time.php";
include __DIR__ . DS . "utils" . DS . "db.php";
include __DIR__ . DS . "utils" . DS . "array_builder.php";
include __DIR__ . DS . "utils" . DS . "objekt.php";
include __DIR__ . DS . "utils" . DS . "fluent_interface.php";
include __DIR__ . DS . "utils" . DS . "math_utils.php";
include __DIR__ . DS . "utils" . DS . "persianTransliterator.php";
include __DIR__ . DS . "utils" . DS . "array_helper.php";
include __DIR__ . DS . "utils" . DS . "reflection_helpers.php";
include __DIR__ . DS . "utils" . DS . "string_helper.php";
include __DIR__ . DS . "utils" . DS . "Fa_Calendar.php";
include __DIR__ . DS . "utils" . DS . "Session.php";
include __DIR__ . DS . "utils" . DS . "session_utils.php";
include __DIR__ . DS . "network_programming" . DS . "network_utils.php";
include __DIR__ . DS . "network_programming" . DS . "examples.php";
include __DIR__ . DS . "network_programming" . DS .  "inc" . DS . "telnet.inc.php";
